<%@ Page Title="Add Account" Language="C#" MasterPageFile="~/Management/ManagementMasterPage.master" AutoEventWireup="true" CodeFile="account_add.aspx.cs" Inherits="Management_account_add" ValidateRequest="false"%>

<%@ Register Src="~/UserControls/MessageUserControl.ascx" TagPrefix="uc1" TagName="MessageUserControl" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Main" Runat="Server">
    <h2>Add Account</h2>
    
    <asp:UpdatePanel runat="server" ChildrenAsTriggers="true" ID="UpdatePanel">
        <ContentTemplate>
            <uc1:MessageUserControl runat="server" ID="MessageUserControl" />
    
	        <div class="centre-form">
		        <div class="form-group row">
			        <label for="FirstNameTextBox" class="col-sm-4 col-form-label right-text">First Name</label>
			        <div class="col-sm-8">
                        <asp:TextBox ID="FirstNameTextBox" name="FirstNameTextBox" runat="server" class="form-control" placeholder="Enter first name here" MaxLength="40" />
			        </div>
		        </div>
		        <div class="form-group row">
			        <label for="LastNameTextBox" class="col-sm-4 col-form-label right-text">Last Name</label>
			        <div class="col-sm-8">
                        <asp:TextBox ID="LastNameTextBox" name="LastNameTextBox" runat="server" class="form-control" placeholder="Enter last name here" MaxLength="40"/>
			        </div>
		        </div>
		        <div class="form-group row">
			        <label for="EmailTextBox" class="col-sm-4 col-form-label right-text">Email</label>
			        <div class="col-sm-8">
                        <asp:TextBox ID="EmailTextBox" name="EmailTextBox" runat="server" class="form-control" placeholder="Enter email here" MaxLength="254"/>
			        </div>
		        </div>

		        <div class="form-group row">
			        <label for="accountType" class="col-sm-4 col-form-label right-text">Authorization Level</label>
			        <div class="col-sm-8 asp-check-and-radio">
                        <asp:RadioButtonList ID="AuthorizationLevelRolesRadioList" runat="server" DataSourceID="AuthorizationRolesNamesODS" DataTextField="RoleName" DataValueField="RoleName" CssClass="check-and-radio-space" AutoPostBack="true">
                        </asp:RadioButtonList>
			        </div>
		        </div>

                <div class="form-group row">
		            <label ID="CareSiteLabel" for="CareSiteDDL" runat="server" class="col-sm-4 col-form-label right-text" visible="false">Care Site</label>
		            <div class="col-sm-8">
                        <asp:DropDownList ID="CareSiteDDL" runat="server" AppendDataBoundItems="true" CssClass="form-control" DataSourceID="GetCareSitesODS" DataTextField="caresitename" DataValueField="caresiteid" Visible="false">
                            <asp:ListItem Value="0">Select...</asp:ListItem>
                        </asp:DropDownList>
		            </div>
	            </div>

		        <p class="note top-space">Usernames and passwords are automatically generated by the system.</p>

		        <div class="form-group row justify-content-center">
                    <asp:LinkButton ID="AddAccountButton" runat="server" CssClass="button button-success" OnClick="AddAccountButton_Click">Add Account</asp:LinkButton>
		        </div>
	        </div>
        </ContentTemplate>
    </asp:UpdatePanel>

    <%-- Object Data Sources --%>
    <asp:ObjectDataSource ID="GetCareSitesODS" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetActiveCareSites" TypeName="MSS.System.BLL.CareSiteController"></asp:ObjectDataSource>
    <asp:ObjectDataSource runat="server" ID="AuthorizationRolesNamesODS" OldValuesParameterFormatString="original_{0}" SelectMethod="ListRoles" TypeName="MSS.System.BLL.Security.RoleManager"></asp:ObjectDataSource>
</asp:Content>

