<%@ Page Title="Manage Account" Language="C#" MasterPageFile="~/Management/ManagementMasterPage.master" AutoEventWireup="true" CodeFile="manage_account.aspx.cs" Inherits="Management_manage_account" ValidateRequest="false" %>

<%@ Register Src="~/UserControls/MessageUserControl.ascx" TagPrefix="uc1" TagName="MessageUserControl" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Main" runat="Server">
    <h2>Manage Account</h2>

    <p class="note">Usernames cannot be edited directly and are generated by the system. The username will change automatically if the first or last name of the account changes.</p>

    <asp:UpdatePanel runat="server" ChildrenAsTriggers="true" ID="UpdatePanel">
        <ContentTemplate>
            <uc1:MessageUserControl runat="server" ID="MessageUserControl" />

            <div class="centre-form">
                <div class="form-group row">
                    <label for="UsernameLabel" class="col-sm-4 col-form-label right-text">Username</label>
                    <asp:Label ID="UsernameLabel" Text="" name="UsernameLabel" runat="server" CssClass="col-sm-8 col-form-label bold"></asp:Label>
                </div>
                <div class="form-group row">
                    <label for="FirstNameTB" class="col-sm-4 col-form-label right-text">First Name</label>
                    <div class="col-sm-8">
                        <asp:TextBox ID="FirstNameTB" name="FirstNameTB" runat="server" class="form-control" MaxLength="40" placeholder="Enter first name here" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="LastNameTB" class="col-sm-4 col-form-label right-text">Last Name</label>
                    <div class="col-sm-8">
                        <asp:TextBox ID="LastNameTB" name="LastNameTB" runat="server" class="form-control" MaxLength="40" placeholder="Enter last name here" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="EmailTB" class="col-sm-4 col-form-label right-text">Email</label>
                    <div class="col-sm-8">
                        <asp:TextBox ID="EmailTB" name="EmailTB" runat="server" class="form-control" MaxLength="254" placeholder="Enter email here"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="accountType" class="col-sm-4 col-form-label right-text">Authorization Level</label>
                    <div class="col-sm-8 asp-check-and-radio">
                        <asp:RadioButtonList ID="AuthorizationLevelRolesRadioList" runat="server" DataSourceID="AuthorizationRolesNamesODS" DataTextField="RoleName" AutoPostBack="true" DataValueField="RoleName" CssClass="check-and-radio-space"></asp:RadioButtonList>
                    </div>
                </div>

                <div class="form-group row bottom-space">
                    <label id="CareSiteLabel" runat="server" for="CareSiteDDL" class="col-sm-4 col-form-label right-text">Care Site</label>

                    <div class="col-sm-8">
                        <asp:DropDownList ID="CareSiteDDL" runat="server" AppendDataBoundItems="true" CssClass="form-control" DataSourceID="GetCareSitesODS" DataTextField="caresitename" DataValueField="caresiteid">
                            <asp:ListItem Value="0">Select...</asp:ListItem>
                        </asp:DropDownList>
                    </div>
                </div>
                <p class="hint">To cancel editing the account, simply navigate to a new page.</p>
                <div class="form-group row justify-content-center top-space">
                    <asp:LinkButton ID="UpdateAccountButton" OnClick="ModifyUser_Click" runat="server" CssClass="button button-primary man-acnt-btn">Update Account</asp:LinkButton>
                    <asp:LinkButton ID="DeactivateAccountButton" runat="server" OnClick="DeactivateUser_Click" OnClientClick="return confirm('Are you sure you want to deactivate this account? This action cannot be undone.')" CssClass="button button-danger second-button man-acnt-btn">Deactivate Account</asp:LinkButton>
                    <asp:LinkButton ID="PasswordBtn" CssClass="button button-warning second-button man-acnt-btn" runat="server" OnClientClick="return confirm('Are you sure you want to reset the password for this account?')" OnClick="ResetPassword_Click">Reset Password</asp:LinkButton>
                </div>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>

    <%-- Object Data Sources --%>
    <asp:ObjectDataSource ID="GetCareSitesODS" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetCareSites" TypeName="MSS.System.BLL.CareSiteController"></asp:ObjectDataSource>
    <asp:ObjectDataSource runat="server" ID="AuthorizationRolesNamesODS" OldValuesParameterFormatString="original_{0}" SelectMethod="ListRoles" TypeName="MSS.System.BLL.Security.RoleManager"></asp:ObjectDataSource>
</asp:Content>


