namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    accesscode
    An entity that links to the accesscode entity in the MSS database.

    PROPERTIES: (generic get/set, no validation)
    public int accesscodeid - the unique ID of the survey (primary key)
    public string accesscodeword - the text of the access code
    public bool activeyn - indicator of whether or not the access code is in rotation (true = active)

    ENTITY LINKS:
    public virtual ICollection<caresiteaccess> - a link to the caresiteaccess entity

    CONSTRUCTORS:
    public accesscode() - the accesscode constructor
    */
    [Table("public.accesscode")]
    public partial class accesscode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accesscode()
        {
            caresiteaccesses = new HashSet<caresiteaccess>();
        }

        public int accesscodeid { get; set; }

        [Required]
        [StringLength(8)]
        public string accesscodeword { get; set; }

        public bool activeyn { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caresiteaccess> caresiteaccesses { get; set; }
    }
}
