namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    caresite
    An entity that links to the caresite entity in the MSS database.

    PROPERTIES: (generic get/set, no validation)
    public int caresiteid - the unique ID of the care site (primary key) 
    public string caresitename - the name of the care site
    public string address - the street address of the care site
    public string city - the city the care site is located in
    public string province - the province the care site is located in
    public bool activeyn - indicates whether a care site is active or not

    ENTITY LINKS:
    public virtual ICollection<caresiteaccess> caresiteaccesses - a link to the caresiteaccess entity
    public virtual ICollection<unit> units - a link to the unit entity

    CONSTRUCTORS:
    public caresite() - the caresite constructor
    */
    [Table("public.caresite")]
    public partial class caresite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caresite()
        {
            caresiteaccesses = new HashSet<caresiteaccess>();
            units = new HashSet<unit>();
        }

        [Key]
        public int caresiteid { get; set; }

        [Required]
        [StringLength(80)]
        public string caresitename { get; set; }

        [Required]
        [StringLength(40)]
        public string address { get; set; }

        [Required]
        [StringLength(30)]
        public string city { get; set; }

        [Required]
        [StringLength(2)]
        public string province { get; set; }

        public bool activeyn { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caresiteaccess> caresiteaccesses { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unit> units { get; set; }

    }
}
