namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /*
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    respondenttype
    An entity that links to the respondenttype table in the database.

    PROPERTIES: (generic get/set, no validation)
    public int respondenttypeid - the unique ID of the respondenttype (primary key)
    public string respondenttypename - the name of the respondenttype
    public bool activeyn - a flag indicating whether the respondenttype is active

    ENTITY LINKS:
    public virtual ICollection<survey> surveys - a link to the list of surveys associated with a respondenttype

    CONSTRUCTORS:
    public respondenttype() - the respondenttype constructor
    */
    [Table("public.respondenttype")]
    public partial class respondenttype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respondenttype()
        {
            surveys = new HashSet<survey>();
        }

        public int respondenttypeid { get; set; }

        [Required]
        [StringLength(15)]
        public string respondenttypename { get; set; }

        public bool activeyn { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> surveys { get; set; }
    }
}
