namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    survey
    An entity that links to the survey entity in the MSS database.

    PROPERTIES: (generic get/set, no validation)
    public int surveyid - the unique ID of the survey (primary key)
    public DateTime date - the date and time that the survey information was collected
    public string firstname - the first name of the survey respondent
    public string bednumber - the bed number of the survey respondent
    public string phonenumber - the phone number of the survey respondent
    public string preferredcontact - the preferred contact method of the survey respondent
    public bool? contactedyn - whether a Survey Respondent has been contacted
    public int agegroupid - the unique ID of the survey respondent's age group
    public int genderid - the unique ID of the survey respondent's gender
    public int respondenttypeid - the unique ID of the survey respondent's respondent type (foreign key) 
    public int unitid - the unique ID of the survey respondent's unit (foreign key) 

    ENTITY LINKS:
    public virtual agegroup agegroup - a link to the agegroup entity
    public virtual gender gender - a link to the gender entity
    public virtual respondenttype respondenttype - a link to the respondenttype entity
    public virtual unit unit - a link to the unit entity
    public virtual ICollection<surveyanswer> surveyanswers - a link to the list of surveyanswers connected to the survey

    CONSTRUCTORS:
    public survey() - the survey constructor
    */
    [Table("public.survey")]
    public partial class survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public survey()
        {
            surveyanswers = new HashSet<surveyanswer>();
        }

        [Key]
        public int surveyid { get; set; }

        [Required]
        public DateTime date { get; set; }

        [StringLength(40)]
        public string firstname { get; set; }

        [StringLength(10)]
        public string bednumber { get; set; }

        [StringLength(14)]
        public string phonenumber { get; set; }

        [StringLength(40)]
        public string preferredcontact { get; set; }

        public bool? contactedyn { get; set; }

        public int agegroupid { get; set; }

        public int genderid { get; set; }

        public int respondenttypeid { get; set; }

        public int unitid { get; set; }

        public virtual agegroup agegroup { get; set; }

        public virtual gender gender { get; set; }

        public virtual respondenttype respondenttype { get; set; }

        public virtual unit unit { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyanswer> surveyanswers { get; set; }
    }
}
