namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    surveyanswer
    An entity that links to the surveyanswer entity in the database.

    PROPERTIES: (generic get/set, no validation)
    public int surveyid - the unique ID of the survey (foreign key)
    public int possibleanswerid - the unique ID of the possible answer (foreign key)
    public string historicalquestion - the question that was posed to the user at the time of response
    public string answer - the response from the user

    ENTITY LINKS:
    public virtual survey survey - a link to the survey entity
    public virtual possibleanswer possibleanswer - a link to the possibleanswer entity

    CONSTRUCTORS:
    None
    */
    [Table("public.surveyanswer")]
    public partial class surveyanswer
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int surveyid { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int possibleanswerid { get; set; }

        [Required]
        [StringLength(250)]
        public string historicalquestion { get; set; }

        [StringLength(250)]
        public string answer { get; set; }

        public virtual survey survey { get; set; }

        public virtual possibleanswer possibleanswer { get; set; }
    }
}
