namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    surveyquestion
    An entity that links to the surveyquestion entity in the MSS database.

    PROPERTIES: (generic get/set, no validation)
    public int surveyquestionid - the unique ID of the surveyquestion (primary key)
    public string question - the wording of the question, shown on the survey
    public string questiontype - the format of the question being asked (multiple choice, written, etc.)
    public bool activeyn - a flag indicating whether the survey question is active

    ENTITY LINKS:
    public virtual ICollection<possibleanswer> possibleanswers - a link to the list of possibleanswers connected to the surveyquestion

    CONSTRUCTORS:
    public surveyquestion() - the surveyquestion constructor
    */
    [Table("public.surveyquestion")]
    public partial class surveyquestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public surveyquestion()
        {
            possibleanswers = new HashSet<possibleanswer>();
        }

        [Key, Required]
        public int surveyquestionid { get; set; }

        [Required]
        [StringLength(250)]
        public string question { get; set; }

        [Required]
        [StringLength(20)]
        public string questiontype { get; set; }

        public bool activeyn { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<possibleanswer> possibleanswers { get; set; }
    }
}
