namespace MSS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /* 
    CREATED:    Generated by ADO.NET Entity Data Model      MAR 6 2018

    unit
    An entity that links to the unit entity in the MSS database.

    PROPERTIES: (generic get/set, no validation)
    public int unitid - the unique ID of the unit (primary key)
    public string unitname - the name of the unit
    public bool activeyn - the active status of the unit
    public int caresiteid - the unique caresite that is associated with the unit (foreign key)

    ENTITY LINKS:
    public virtual caresite caresite - a link to the caresite entity
    public virtual ICollection<survey> surveys - a link to the list of surveys connected to the unit

    CONSTRUCTORS:
    public unit() - the unit constructor
    */
    [Table("public.unit")]
    public partial class unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unit()
        {
            surveys = new HashSet<survey>();
        }

        public int unitid { get; set; }

        [Required]
        [StringLength(60)]
        public string unitname { get; set; }

        public bool activeyn { get; set; }

        public int caresiteid { get; set; }

        public virtual caresite caresite { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<survey> surveys { get; set; }
    }
}
